# Generated by Django 5.1.6 on 2025-06-17 08:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aperd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pic', models.CharField(max_length=500)),
                ('progress', models.CharField(choices=[('On Board', 'On Board'), ('OPS Memo', 'OPS Memo'), ('MPD', 'MPD'), ('Next Action', 'Next Action'), ('PKS', 'PKS'), ('PKS 2', 'PKS 2'), ('Resiprokal Transaksi', 'Resiprokal Transaksi')], default=None, max_length=200)),
                ('desc', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Under Review', 'Under Review'), ('Published', 'Published'), ('Freeze', 'Freeze'), ('Paused', 'Paused')], default=None, max_length=200)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aperd', models.ManyToManyField(to='myapp.aperd')),
            ],
        ),
        migrations.CreateModel(
            name='AumData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('aum', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Asset Under Management (IDR)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aperd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.aperd', verbose_name='APERD SA')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
