# Generated by Django 5.1.6 on 2025-06-20 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aumdata',
            unique_together=set(),
        ),
    ]
